### PR TITLE
Custom framework branch

### PR DESCRIPTION
**Pull request by christianotieno**

### CODE REVIEW

**Review by Redvanisation — APPROVED** [review]
# Changes required  🛑

### Hello team  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. Please fix the linter errors.

2. Please Validate and fix the HTML markup [here](https://validator.w3.org/#validate_by_input)

3. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.


### [OPTIONAL]

#### Margins
- [ ]  The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
- [ ]  The margins should span from 0 rem to 1 rem
- [ ]  The margins should have breakpoints (e.g. margin-sm-top-1)


#### Padding
- [ ]  The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
- [ ]  The padding should span from 0 rem to 1 rem
- [ ]  The padding should have breakpoints (example padding-lg-2)

#### Floats

* [x] The CSS files define separate classes for float left, right and clearing the floats

#### Positions

* [x] The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

#### Display properties

The CSS files define:

* [x] A class to set the display property of an element to flex
* [x] A class to set the display property to hidden
* [x] A class to set the display property to none
* [x] The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

* [x] Classes to set vertical alignment as top, bottom or center
* [x] Classes to set horizontal alignment as left, right or center

#### Background and text

The CSS files define:

* [x] At least ten different classes to set the background and text colors of an element

#### Utilities

The CSS files define:

* [x] Classes to horizontally align text to the left, right or center
* [ ] At least five classes to set the font size of an element
* [ ] Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* [ ] The CSS files define separate classes for border top, bottom, left, right, all border
* [ ] The border should span from 0 to 1rem
* [ ] The border should have classes for making box round
* [ ] The border should have a class defined to transform a box into a circle


### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!  image
 Great job! Wow, your README is very detailed. Love the effort you have put in. Looks image
 Not quite there just yet image

### Some Required Changes

### [OPTIONAL]
### Box utilities
#### Margins
- [x] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
- [x] The margins should span from 0 rem to 1 rem
- [ ] The margins should have breakpoints (e.g. margin-sm-top-1)
#### Padding
- [ ] The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
- [ ] The padding should span from 0 rem to 1 rem
- [ ] The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Positions

* [x] Please add separate classes to change the position property of an element to 'absolute', you have just 'fixed', 'static' and 'relative'.

### Display

#### Display properties

The CSS files define:

* [x] A class to set the display property to hidden
* [ ] The none class should have breakpoints (example display-md-none)

### Text
#### Utilities
The CSS files define:

- [x] Classes to horizontally align text to the left, right or center
- [x] At least five classes to set the font size of an element
- [x] Three classes to set the font weight of an element (bold, normal, medium)

#### Border
- [x] The CSS files define separate classes for border top, bottom, left, right, all border
- [x] The border should span from 0 to 1rem
- [x] The border should have classes for making box round
- [x] The border should have a class defined to transform a box into a circle


Remember to use semantic HTML. Please read more here : [HTML5 Semantic Elements](https://www.w3schools.com/html/html5_semantic_elements.asp)
Screenshot from 2019-11-05 22-59-57


#### Please check responsiveness:
- [ ] breakpoint for small screens with a width of up to 720px




Breakpoints


 The CSS files should define a breakpoint for small screens with a width of up to 720px

- [ ]  in the range of 720px - 1024px





- [ ] for large screens with width above 1024px
### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Comment by christianotieno** [comment]
Complied with most of the optional recommendations.

**Review by suretrust — APPROVED** [review]
### Amazing job! Let's get this merged! :+1: 

_Good luck with your future projects and happy coding! :tada:_

**Pull request merged**
